# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hndcam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hndcam.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0chndcam.proto\"\x07\n\x05\x45mpty\"\x16\n\x06\x43\x61mImg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x85\x01\n\x03\x43\x61m\x12\x1e\n\tgetrc0img\x12\x06.Empty\x1a\x07.CamImg\"\x00\x12\x1e\n\tgetrc1img\x12\x06.Empty\x1a\x07.CamImg\"\x00\x12\x1e\n\tgetlc0img\x12\x06.Empty\x1a\x07.CamImg\"\x00\x12\x1e\n\tgetlc1img\x12\x06.Empty\x1a\x07.CamImg\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=23,
)


_CAMIMG = _descriptor.Descriptor(
  name='CamImg',
  full_name='CamImg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='CamImg.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['CamImg'] = _CAMIMG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'hndcam_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

CamImg = _reflection.GeneratedProtocolMessageType('CamImg', (_message.Message,), dict(
  DESCRIPTOR = _CAMIMG,
  __module__ = 'hndcam_pb2'
  # @@protoc_insertion_point(class_scope:CamImg)
  ))
_sym_db.RegisterMessage(CamImg)



_CAM = _descriptor.ServiceDescriptor(
  name='Cam',
  full_name='Cam',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=50,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='getrc0img',
    full_name='Cam.getrc0img',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMIMG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getrc1img',
    full_name='Cam.getrc1img',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMIMG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getlc0img',
    full_name='Cam.getlc0img',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMIMG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getlc1img',
    full_name='Cam.getlc1img',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMIMG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAM)

DESCRIPTOR.services_by_name['Cam'] = _CAM

# @@protoc_insertion_point(module_scope)
