# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frtknt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frtknt.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x66rtknt.proto\"\x07\n\x05\x45mpty\"\x15\n\x05MatKW\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"$\n\x04Pair\x12\r\n\x05\x64\x61ta0\x18\x01 \x01(\x05\x12\r\n\x05\x64\x61ta1\x18\x02 \x01(\x05\"b\n\x0ePartialPcdPara\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x14\n\x05width\x18\x02 \x01(\x0b\x32\x05.Pair\x12\x15\n\x06height\x18\x03 \x01(\x0b\x32\x05.Pair\x12\x15\n\x05matkw\x18\x04 \x01(\x0b\x32\x06.MatKW\"\x1b\n\x0bReturnValue\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x8f\x02\n\x03Knt\x12%\n\x0bgetrgbarray\x12\x06.Empty\x1a\x0c.ReturnValue\"\x00\x12\'\n\rgetdeptharray\x12\x06.Empty\x1a\x0c.ReturnValue\"\x00\x12%\n\x0bgetdepthraw\x12\x06.Empty\x1a\x0c.ReturnValue\"\x00\x12%\n\x0bgetpcdarray\x12\x06.MatKW\x1a\x0c.ReturnValue\"\x00\x12\x35\n\x12getpartialpcdarray\x12\x0f.PartialPcdPara\x1a\x0c.ReturnValue\"\x00\x12\x33\n\x1amapColorPointToCameraSpace\x12\x05.Pair\x1a\x0c.ReturnValue\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=23,
)


_MATKW = _descriptor.Descriptor(
  name='MatKW',
  full_name='MatKW',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='MatKW.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=46,
)


_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data0', full_name='Pair.data0', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data1', full_name='Pair.data1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=84,
)


_PARTIALPCDPARA = _descriptor.Descriptor(
  name='PartialPcdPara',
  full_name='PartialPcdPara',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PartialPcdPara.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='PartialPcdPara.width', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='PartialPcdPara.height', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matkw', full_name='PartialPcdPara.matkw', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=184,
)


_RETURNVALUE = _descriptor.Descriptor(
  name='ReturnValue',
  full_name='ReturnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ReturnValue.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=213,
)

_PARTIALPCDPARA.fields_by_name['width'].message_type = _PAIR
_PARTIALPCDPARA.fields_by_name['height'].message_type = _PAIR
_PARTIALPCDPARA.fields_by_name['matkw'].message_type = _MATKW
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['MatKW'] = _MATKW
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['PartialPcdPara'] = _PARTIALPCDPARA
DESCRIPTOR.message_types_by_name['ReturnValue'] = _RETURNVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'frtknt_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

MatKW = _reflection.GeneratedProtocolMessageType('MatKW', (_message.Message,), dict(
  DESCRIPTOR = _MATKW,
  __module__ = 'frtknt_pb2'
  # @@protoc_insertion_point(class_scope:MatKW)
  ))
_sym_db.RegisterMessage(MatKW)

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), dict(
  DESCRIPTOR = _PAIR,
  __module__ = 'frtknt_pb2'
  # @@protoc_insertion_point(class_scope:Pair)
  ))
_sym_db.RegisterMessage(Pair)

PartialPcdPara = _reflection.GeneratedProtocolMessageType('PartialPcdPara', (_message.Message,), dict(
  DESCRIPTOR = _PARTIALPCDPARA,
  __module__ = 'frtknt_pb2'
  # @@protoc_insertion_point(class_scope:PartialPcdPara)
  ))
_sym_db.RegisterMessage(PartialPcdPara)

ReturnValue = _reflection.GeneratedProtocolMessageType('ReturnValue', (_message.Message,), dict(
  DESCRIPTOR = _RETURNVALUE,
  __module__ = 'frtknt_pb2'
  # @@protoc_insertion_point(class_scope:ReturnValue)
  ))
_sym_db.RegisterMessage(ReturnValue)



_KNT = _descriptor.ServiceDescriptor(
  name='Knt',
  full_name='Knt',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=216,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='getrgbarray',
    full_name='Knt.getrgbarray',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getdeptharray',
    full_name='Knt.getdeptharray',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getdepthraw',
    full_name='Knt.getdepthraw',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getpcdarray',
    full_name='Knt.getpcdarray',
    index=3,
    containing_service=None,
    input_type=_MATKW,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getpartialpcdarray',
    full_name='Knt.getpartialpcdarray',
    index=4,
    containing_service=None,
    input_type=_PARTIALPCDPARA,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='mapColorPointToCameraSpace',
    full_name='Knt.mapColorPointToCameraSpace',
    index=5,
    containing_service=None,
    input_type=_PAIR,
    output_type=_RETURNVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KNT)

DESCRIPTOR.services_by_name['Knt'] = _KNT

# @@protoc_insertion_point(module_scope)
