# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import robotcon.rpc.frtknt.frtknt_pb2 as frtknt__pb2


class KntStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getrgbarray = channel.unary_unary(
        '/Knt/getrgbarray',
        request_serializer=frtknt__pb2.Empty.SerializeToString,
        response_deserializer=frtknt__pb2.ReturnValue.FromString,
        )
    self.getdeptharray = channel.unary_unary(
        '/Knt/getdeptharray',
        request_serializer=frtknt__pb2.Empty.SerializeToString,
        response_deserializer=frtknt__pb2.ReturnValue.FromString,
        )
    self.getdepthraw = channel.unary_unary(
        '/Knt/getdepthraw',
        request_serializer=frtknt__pb2.Empty.SerializeToString,
        response_deserializer=frtknt__pb2.ReturnValue.FromString,
        )
    self.getpcdarray = channel.unary_unary(
        '/Knt/getpcdarray',
        request_serializer=frtknt__pb2.MatKW.SerializeToString,
        response_deserializer=frtknt__pb2.ReturnValue.FromString,
        )
    self.getpartialpcdarray = channel.unary_unary(
        '/Knt/getpartialpcdarray',
        request_serializer=frtknt__pb2.PartialPcdPara.SerializeToString,
        response_deserializer=frtknt__pb2.ReturnValue.FromString,
        )
    self.mapColorPointToCameraSpace = channel.unary_unary(
        '/Knt/mapColorPointToCameraSpace',
        request_serializer=frtknt__pb2.Pair.SerializeToString,
        response_deserializer=frtknt__pb2.ReturnValue.FromString,
        )


class KntServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getrgbarray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getdeptharray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getdepthraw(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getpcdarray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getpartialpcdarray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mapColorPointToCameraSpace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KntServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getrgbarray': grpc.unary_unary_rpc_method_handler(
          servicer.getrgbarray,
          request_deserializer=frtknt__pb2.Empty.FromString,
          response_serializer=frtknt__pb2.ReturnValue.SerializeToString,
      ),
      'getdeptharray': grpc.unary_unary_rpc_method_handler(
          servicer.getdeptharray,
          request_deserializer=frtknt__pb2.Empty.FromString,
          response_serializer=frtknt__pb2.ReturnValue.SerializeToString,
      ),
      'getdepthraw': grpc.unary_unary_rpc_method_handler(
          servicer.getdepthraw,
          request_deserializer=frtknt__pb2.Empty.FromString,
          response_serializer=frtknt__pb2.ReturnValue.SerializeToString,
      ),
      'getpcdarray': grpc.unary_unary_rpc_method_handler(
          servicer.getpcdarray,
          request_deserializer=frtknt__pb2.MatKW.FromString,
          response_serializer=frtknt__pb2.ReturnValue.SerializeToString,
      ),
      'getpartialpcdarray': grpc.unary_unary_rpc_method_handler(
          servicer.getpartialpcdarray,
          request_deserializer=frtknt__pb2.PartialPcdPara.FromString,
          response_serializer=frtknt__pb2.ReturnValue.SerializeToString,
      ),
      'mapColorPointToCameraSpace': grpc.unary_unary_rpc_method_handler(
          servicer.mapColorPointToCameraSpace,
          request_deserializer=frtknt__pb2.Pair.FromString,
          response_serializer=frtknt__pb2.ReturnValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Knt', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
